### ISSUE TITLE
Db-input: min / max attribute not passed through

### ISSUE THREAD

**Issue by juthilo** [db-ui/elements#1114]
I haven't tested all the validation attributes, but at least `min` and `max` aren't passed down to the actual `input` from `db-input`.

**Comment by mfranzke** [comment]
I've used the table on https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation#validation-related_attributes to identify `max`, `min` and `step` as missing attributes for Constraint Validation.

**Comment by mfranzke** [comment]
I've used the table on https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation#validation-related_attributes to identify `max`, `min` and `step` as missing attributes for Constraint Validation.

**Comment by juthilo** [comment]
😍 thanks a lot for the quick fix

**Comment by mfranzke** [comment]
> 😍 thanks a lot for the quick fix

thanks a lot for your contribution.
