### ISSUE TITLE
Extra margin for icons in db-link cause all icons to have extra margin

### ISSUE THREAD

**Issue by juthilo** [db-ui/elements#1470]
There's a rule for 6px additional margin-right after icons in the styles for db-link:

https://github.com/db-ui/elements/blob/main/packages/db-ui-elements-stencil/src/components/db-link/db-link.scss#L5

Because this rule isn't scoped to `.elm-link`, this causes the rule `db-icon { margin-right: 0.375rem; }` to appear on all pages containing db-links. All the icons on the page get the additional margin, causing some very weird looks in tags and buttons.

I'd be happy to fix it in a PR, just wanted to ask first whether the extra margin is intended or if the rule should be removed altogether.

**Comment by mfranzke** [comment]
@juthilo as always, good catch, thanks a lot !

**Comment by juthilo** [comment]
glad to help! thanks for the quick fix, I would never have guessed that that's what this rule was for

**Comment by mfranzke** [comment]
> glad to help! thanks for the quick fix, I would never have guessed that that's what this rule was for

As this code is even already a little older, I needed to look up within the previous inner source repo actually.
