### ISSUE TITLE
Feature request: Checkbox without visible label

### ISSUE THREAD

**Issue by juthilo** [db-ui/elements#1509]
We're currently using checkboxes in front of inputs on a search page to let users quickly activate/de-activate a filter.

This causes problems for a11y because it is not possible to add a hidden label for users using assistive technology.

It would be great if there was an option to mark a checkbox as "checkonly" causing the label text to be invisible to sighted users. This would be similar to icononly buttons with text, where the text next to the icon gets hidden as well.

**Comment by juthilo** [comment]
I'm not fully up to date with the state of the art regarding accessibility.

However, in a simplistic view, I would say there are reasonable use cases for a checkbox which conveys it's meaning to users that can read a screen. In our case, we want users to be able to switch custom text filter controls on and off without losing the text they entered.

Requiring a visible label in this case would make the page more complicated for sighted users IMO.

Regarding the chip pattern, I think the current checkbox solution is understood more easily. I think the toggle pattern might also make sense, but as far as I remember that doesn't currently work well with Angular's reactivity.

**Comment by juthilo** [comment]
For what it's worth, after some more consideration, we have now removed the checkboxes from our solution altogether. So maybe the use case isn't actually that strong or at least otherwise achievable. 😄

**Comment by mfranzke** [comment]
@juthilo thanks a lot for your feedback. In this case I would like to close this issue for the moment than.
