### ISSUE TITLE
Missing referenced icons

### ISSUE THREAD

**Issue by mfranzke** [db-ui/elements#163]
Icons within components (`db-input[type=search]` and `db-select`) are referenced by a path, that's relative to the pages path instead of CSS path, as we're inlining the CSS for the Custom Elements.

That for the easiest and most stable is to include these icons base64 encoded. We shouldn't implement this in DB UI Core directly, as we'd still like to reference all the assets in there in general, but only include it as base64 for the specific use case of inlined CSS by DB UI Elements.

**Comment by nmerget** [comment]
Could this be a solution https://github.com/amzn/style-dictionary/tree/main/examples/advanced/assets-base64-embed?

**Comment by mfranzke** [comment]
@nmerget That would be a good solution as well, but I would like to keep the tokens simple, as this is only a bypass for the inline CSS rendering within the Custom Components.
