### ISSUE TITLE
Icon "check-circle" not visible

### ISSUE THREAD

**Issue by ma8642** [db-ui/elements#2013]
Issue:
When I try to use the icon "check-circle" it does not display.

Code:
```
<db-icon
  icon="check-circle"
  variant="32-outline"
  class="hydrated"
></db-icon>
```

More details:
It doesn't matter if I change the variant to 32-filled. Still doesn't show.
When I try replacing this icon with "komfort-check-in-check" I have no issues. I did not change any other code except the string after `icon=`. I changed it back to check-circle and it does not show.
I am using Typescript and Vue 3.

Thanks in advance!

**Comment by mfranzke** [comment]
Hi @ma8642 thanks a lot for reaching out.

I've just tried to reproduce this aspect on https://db-ui.github.io/elements/?path=/docs/db-icon--live-demo and it does work over there:
<img width="1036" alt="image" src="https://github.com/db-ui/elements/assets/787658/055e3895-7ff4-4867-93d8-3083796ee0f8">

I'm struggling what might be the reason for having it not working in your context.

**Comment by LarsVanEgmond** [comment]
I have the same issue with React


If I use the Component 
              `<DbIcon icon="check-circle"></DbIcon>`
              
The Icon does not show.
If I use it in a span it shows:
`<span data-icon="check-circle"></span>`

**Comment by ma8642** [comment]
Solution: I updated my db-ui version to 0.28.0 in the package.json and now I am able to use the icon!
