### ISSUE TITLE
Calendar icon showing different emoji

### ISSUE THREAD

**Issue by ma8642** [db-ui/elements#2207]
# Issue:
When trying to use the "calendar" icon, it is replaced by a non-db calendar emoji.

# Media:
## Here's how I have implemented the calendar icon in my code (and also another icon for comparison)
![calendarcode](https://github.com/db-ui/elements/assets/13713037/c3875174-9141-4449-978d-10de032ee79d)
![multipleticketscode](https://github.com/db-ui/elements/assets/13713037/b987539a-4825-4887-b632-78873ce045ab)

## and here is how it appears:
Calendar:
![outcomecalendar](https://github.com/db-ui/elements/assets/13713037/bf62afad-8b72-4f61-9a8a-eedd7e94647e)
Multiple Tickets (shows correctly):
![outcomemultipletickets](https://github.com/db-ui/elements/assets/13713037/78d6334f-3bb9-468a-ae38-8a3b2ea99877)

## Other things I have tried:
- Importing DbIcon and using that component instead but there is no difference.
- Using scss mixin version of the icon, but copying the example mixin code gives me a syntax error. [Phind explanation](https://www.phind.com/search?cache=i2onsdtbs32ae0kf52df3ks0).

## Stackoverflow:
[Possibly related](https://stackoverflow.com/a/36211322/9222529) but there is so fonts/db-ui in node modules so I don't know how to do this for db-ui icons.
 
# My Stack:
Framework: Vue 3
Browser: chrome and firefox

**Comment by mfranzke** [comment]
@ma8642 thanks a lot for your request. Does a 404 / _not found_ come up in your network tab in case of trying to display the calendar icon?

**Comment by ma8642** [comment]
No, no 404s and nothing in the network tab about fonts or icons.

**Comment by ma8642** [comment]
@mfranzke No, no 404s and nothing in the network tab about fonts or icons.

**Comment by ma8642** [comment]
Solution: I updated my db-ui version to 0.28.0 in the package.json and now I am able to use the icon!
