### ISSUE TITLE
docs: start page isn't correct

### ISSUE THREAD

**Issue by mfranzke** [db-ui/elements#2537]
https://db-ui.github.io/elements/?path=/story/00-intro-welcome--page

**Comment by mfranzke** [comment]
Sorry, I thought that I've opened the general URL https://db-ui.github.io/elements/ and would have been redirect to this one.

**Comment by nmerget** [comment]
![image](https://github.com/db-ui/elements/assets/104347736/c7923b2d-125c-4616-b99c-aef1b247b874)
Ahh found it the links of the cards are wrong
