### ISSUE TITLE
Version 0.30.0: Could not resolve "@db-ui/ngx-elements-enterprise/dist/lib"

### ISSUE THREAD

**Issue by jonaskuske** [db-ui/elements#2606]
In versions 0.29.3 and below, `@db-ui/ngx-elements-enterprise` [included a separate `package.json` in `dist/lib`](https://unpkg.com/browse/@db-ui/ngx-elements-enterprise@0.29.3/dist/lib/package.json) that pointed at the entry file(s), so that the following import worked (as suggested by the docs):

```ts
import { DBUIElementsModule } from '@db-ui/ngx-elements-enterprise/dist/lib';
```

Now in version 0.30.0, [this `package.json` is missing](https://unpkg.com/browse/@db-ui/ngx-elements-enterprise@0.30.0/dist/lib/). As there's also no `index.js`, the import from `dist/lib` can not be resolved and the application build errors:

```
Application bundle generation failed. [4.257 seconds]

✘ [ERROR] Could not resolve "@db-ui/ngx-elements-enterprise/dist/lib"

    src/app/app.module.ts:13:35:
      13 │ ...UIElementsModule } from '@db-ui/ngx-elements-enterprise/dist/lib';
```

**Comment by mfranzke** [comment]
@jonaskuske thanks a lot for your feedback. We've just released a possible solution within a prerelease with the @next tag as version [`0.30.1-0-7bca155`](https://www.npmjs.com/package/@db-ui/ngx-elements/v/0.30.1-0-7bca155).

**Comment by jonaskuske** [comment]
@mfranzke Thanks! I just tested it, unfortunately it doesn't work. 🙁

(and if you check https://unpkg.com/browse/@db-ui/ngx-elements-enterprise@0.30.1-0-7bca155/dist/lib/, there's still neither an `index.js` nor a `package.json`, so the import from there can't be resolved)

**Comment by mfranzke** [comment]
@nmerget I think that you might have thought about your solution a little differently. Could you please come back to this aspect and further explain ?

**Comment by mfranzke** [comment]
> @mfranzke Thanks! I just tested it, unfortunately it doesn't work. 🙁
> 
> (and if you check https://unpkg.com/browse/@db-ui/ngx-elements-enterprise@0.30.1-0-7bca155/dist/lib/, there's still neither an `index.js` nor a `package.json`, so the import from there can't be resolved)

@jonaskuske The `package.json` is back at its expected place. Could you please retest with version `0.30.1-2-003f1c3`?

**Comment by jonaskuske** [comment]
@mfranzke `0.30.1-2-003f1c3` works 👍

**Comment by mfranzke** [comment]
> @mfranzke `0.30.1-2-003f1c3` works 👍

great, thanks. I've started the release pipeline for a patch release with version `0.30.1`
