### ISSUE TITLE
Link to Live Code Demo Page is Broken

### ISSUE THREAD

**Issue by ma8642** [db-ui/elements#2724]
Issue:
I was on [this page](https://db-ui.github.io/elements/?path=/docs/05-data-input-input-intro--docs) and I clicked the link to the [live demo page](https://db-ui.github.io/story/db-input--live-demo) but arrived on a 404 not found page.
<img width="1167" alt="Screenshot 2024-08-16 at 12 50 00" src="https://github.com/user-attachments/assets/2057c63d-2e68-4618-85c1-2ba614de6dc0">

**Comment by mfranzke** [comment]
@ma8642 thanks a lot for your new feedback. I'll take of this with a new release.
