### ISSUE TITLE
Some review branch deployments aren't accessible

### ISSUE THREAD

**Issue by mfranzke** [db-ui/elements#308]
Some of the review branch deployments aren't accessible / are responding by a 404:
- https://db-ui.github.io/elements/review/refactor-aligned-scripts/?path=/story/00-intro-welcome--page
- https://db-ui.github.io/elements/review/refactor-guidelines-3-button-style/?path=/story/00-intro-welcome--page
- https://db-ui.github.io/elements/review/refactor-guidelines-3-checkbox-style/?path=/story/00-intro-welcome--page
- https://db-ui.github.io/elements/review/refactor-html-on-two-components/?path=/story/00-intro-welcome--page

**Comment by nmerget** [comment]
I guess the pipeline failed before the deployment step could upload to gh-pages:

https://github.com/db-ui/elements/actions/runs/3156526435/jobs/5136334115
