### ISSUE TITLE
Db-icon and Db-Button not working 

### ISSUE THREAD

**Issue by EmilAlipiev** [db-ui/elements#419]
https://db-ui.github.io/elements/version/v0.16.1/?path=/docs/db-icon--live-demo

on the playground is also seen that db-icon is not working at all and this effects db-button as well using with db-icon together.

Workaround for `db-button` setting `    data-icon=edit `attribute

**Comment by mfranzke** [comment]
@EmilAlipiev thanks a lot for your feedback.

This is most likely related to that DB UI Core stylesheets aren't correctly rendering the icons declarations for the regular / non-enterprise styling, that we're using within our DB UI Elements examples.

As this is a known bug, we're even already working on releasing the solution.
