### ISSUE TITLE
db-link: Property `current` is not updated after changes

### ISSUE THREAD

**Issue by mschorsch** [db-ui/elements#590]
The property `current` is not updated when there are changes.

__Reproducer__
1. `yarn create react-app my-app --template typescript`
2. `yarn add @db-ui/react-elements-enterprise`
3. Follow the [Get started with React](https://db-ui.github.io/elements/iframe.html?viewMode=story&id=00-intro-frameworks-react--page&args=#get-started-with-react)
4. Add the following code to you `App.tsx`

```typescript
// App.tsx
import "@db-ui/core/dist/css/db-ui-core.vars.css"
import {DbFooter, DbHeader, DbLink, DbMainnavigation, DbPage} from "@db-ui/react-elements-enterprise";
import {useState} from "react";

function App() {
    const [active, setActive] = useState(true);

    return (
        <>
            <DbPage>
                <DbHeader slot="header">
                    <button onClick={() => setActive(!active)}>Toggle</button>
                    <DbMainnavigation>
                        <DbLink href="/" key="key1" current={active ? "page" : "false"}>First</DbLink>
                        <DbLink href="/whatever" key="key2" current={active ? "false" : "page"}>Second</DbLink>
                    </DbMainnavigation>
                    <div/>
                </DbHeader>
                <DbFooter slot="footer" copyright border/>
            </DbPage>
        </>
    );
}

export default App;
```
5. `yarn start`
6. Press the button `Toggle`

__Expected behaviour__

The active page should toggle between "First" and "Second"

**Comment by mschorsch** [comment]
Seems related: https://github.com/db-ui/elements/issues/394#issuecomment-1286726697

**Comment by dkolba** [comment]
Issue is reproducible.

Culprit seem to be the ```componentWillLoad()``` lifecycle method of ```<DbMainnavigation>```, which will not trigger a re-render of "children" upon a change.  ```<DbLink>``` works as expected when not being wrapped by ```<DbMainnavigation>```
