### ISSUE TITLE
docs: Big Picture link is broken

### ISSUE THREAD

**Issue by d-koppenhagen** [db-ui/elements#604]
The "Big Picture" Link [here](https://github.com/db-ui/elements/blob/main/doc/README.md) is broken.
It links to:
https://github.com/db-ui/elements/blob/main/doc/architecture.md

**Comment by mfranzke** [comment]
Sadly this document hasn't ever been filled with content, we've only documented a lot of aspects in our internal wiki. That for the easiest for the moment is to remove it and follow up with an ADR for new decisions; we'll even give an overview regarding the big picture after finishing the evaluation of some of the next decisions.
