### ISSUE TITLE
Docs: describe how to integrate `@db-ui/elements` stories into own storybook

### ISSUE THREAD

**Issue by d-koppenhagen** [db-ui/elements#707]
It would be nice to have a small docs section which describes how to include the `@db-ui/elements` storybook into an own storybook within a specific project like this:

```js
module.exports = {
  // ...
  refs: {
    "@db-ui/elements": {
      title: "@db-ui/elements",
      url: "https://db-ui.github.io/elements",
      expanded: false, // optional, true, when expanded by default
    },
  },
}
```

This should lead into something like this:

![Bildschirm­foto 2022-12-13 um 09 41 27](https://user-images.githubusercontent.com/4279702/207268050-d1ed6925-7a94-4a86-925b-c271702faa90.png)

**Comment by mfranzke** [comment]
@d-koppenhagen thanks a lot for your suggestion. Would it be possible that you even also provide a PR for this? Might be an easy thing even for us, but it's especially interesting to get to know where we should place an information like this within our docs / where you would have searched for it.
