### ISSUE TITLE
Db-icon warning not working

### ISSUE THREAD

**Issue by EmilAlipiev** [db-ui/elements#746]
Although Marketing page has warning icon available and under icons>functional i can see that warning icon is also available

![image](https://user-images.githubusercontent.com/10422347/208728262-44ba5285-9298-49fa-947a-34c138c442c0.png)

using on db-icon like below on the playground, it wont be displayed. I tried error, info etc, working fine.

![image](https://user-images.githubusercontent.com/10422347/208728569-ce96c9fc-fcd1-4f1c-87f3-d3c6f4db3b0b.png)

**Comment by mfranzke** [comment]
Hi @EmilAlipiev, thanks a lot for your feedback. Sadly those icons aren't up to date at the moment – we'll update them asap.
